title: "ConfigMyApp"
description: AppDynamics configuration as code tool"
# remote_theme: pmarsceill/just-the-docs
remote_theme: rundocs/jekyll-rtd-theme

baseurl: '/ConfigMyApp'
url: ''
fluid: true
#logo: "logo.png"

readme_index:
  with_frontmatter: true

author: AppDynamics

copyright:
  #since: 2020 # like: 2000
  revision: false # is show the revision
  
docker_url: 'https://hub.docker.com/r/appdynamicscx/configmyapp'
addons: false 
addons:
  - github
  - analytics
  
edit: true
addons_commit: false # defualt
