title: "ConfigMyApp"
description: "description"
# remote_theme: pmarsceill/just-the-docs
remote_theme: rundocs/jekyll-rtd-theme

baseurl: '/ConfigMyApp'
url: ''
fluid: true
logo: "https://user-images.githubusercontent.com/2548160/68075860-ba631e80-fda5-11e9-8457-07859944ae08.png"

readme_index:
  with_frontmatter: true

author: AppDynamics

copyright:
  #since: 2020 # like: 2000
  revision: false # is show the revision
  
docker_url: 'https://hub.docker.com/r/appdynamicscx/configmyapp'
#addons: false 
addons:
  - github
  - analytics
  
edit: true
addons_commit: false # defualt
