version: '3.3'
services:
    delegate:
        hostname: harness-delegate # register under the same name in Harness.io UI
        restart: unless-stopped
        env_file:
            - harness-variables.env
        image: 'harness/delegate:latest'