harnessApiVersion: '1.0'
type: BUILD
notificationRules:
- conditions:
  - FAILED
  executionScope: WORKFLOW
  notificationGroupAsExpression: false
  userGroupAsExpression: false
  userGroupIds:
  - YqN5jEuwQLeE7FSQitFG9A
phases:
- daemonSet: false
  name: Phase 1
  phaseSteps:
  - type: PREPARE_STEPS
    name: Prepare Steps
    stepsInParallel: false
  - type: COLLECT_ARTIFACT
    name: Collect Artifact
    steps:
    - type: SHELL_SCRIPT
      name: Shell Script
      properties:
        commandPath: null
        connectionAttributes: null
        executeOnDelegate: true
        host: null
        outputVars: ''
        publishAsVar: false
        scriptString: "echo \"Hello world!\"\napt-get -y install git\ngit --version\n\
          echo \"remote\"\ngit config remote.origin.url https://github.com/Appdynamics/ConfigMyApp.git\n\
          echo \"Cloning repo...\" \ngit config --global credential.helper cache\n\
          git clone https://AlexJov:fa64a47df9c0fc8ae6bbff0c77d7ffea14737e24@github.com/Appdynamics/ConfigMyApp.git\
          \ -b features/jenkins_pipeline --single-branch ConfigMyApp2  --bare\necho\
          \ \"Cloned\"\nls\nwhoami\ncd ConfigMyApp2\n./configMyApp.sh TPV no no dev\n\
          echo \"Done.\""
        scriptType: BASH
        sshKeyRef: null
        sweepingOutputName: null
        sweepingOutputScope: null
        tags: null
        templateExpressions: null
        templateUuid: null
        templateVariables: null
        templateVersion: null
        timeoutMillis: 180000
    stepsInParallel: false
  - type: WRAP_UP
    name: Wrap Up
    stepsInParallel: false
  provisionNodes: false
  statefulSet: false
templatized: false
userVariables:
- type: TEXT
  allowedValues: dev,qa,prod,test
  fixed: true
  mandatory: true
  name: APP_ENVIRONMENT
  value: dev
