apiVersion: v1
data:
  configBT.json: "{ \n    \"java_pojo_rules\": [\n       {\n        \"include_or_exclude_rule\":
    \"exclude\",\n        \"rule_name\": \"getStatus_test\",\n        \"class_name\":
    \"com.appdynamics.health.Class\",\n        \"class_matching_condition\":\"STARTS_WITH\",\n
    \       \"method_name\": \"getStatus\",\n        \"method_matching_condition\":\"EQUALS\",\n
    \       \"priority\":\"10\"\n       }\n     ],\n\n     \"dotnet_poco_rules\":
    [\n      {\n        \"include_or_exclude_rule\": \"INCLUDE\",\n        \"rule_name\":
    \"GetMQTopic_test\",\n        \"class_name\": \"Services.IO.DequeueSync\",\n        \"class_matching_condition\":\"STARTS_WITH\",\n
    \       \"method_name\": \"GetMQTopic\",\n        \"method_matching_condition\":\"EQUALS\",\n
    \       \"priority\":\"0\"\n       },\n       {\n        \"include_or_exclude_rule\":
    \"EXCLUDE\",\n        \"rule_name\": \"UserLogin\",\n        \"class_name\": \"AppD.Ecom.AuthNTest\",\n
    \       \"class_matching_condition\":\"STARTS_WITH\",\n        \"method_name\":
    \"Login\",\n        \"method_matching_condition\":\"CONTAINS\",\n        \"priority\":\"0\"\n
    \      }\n    ],\n\n     \"dotnet_asp_rules\": [\n      {\n       \"include_or_exclude_rule\":
    \"Include\",\n       \"rule_name\": \"ASPLogin_test\",\n       \"matching_condition\":\"CONTAINS\",\n
    \      \"matching_strings\": \"/login\",\n       \"priority\":\"8\"\n      }\n
    \   ],\n\n    \"java_servlet_rules\": [\n      {\n       \"rule_name\": \"LogonServlet_test\",\n
    \      \"matching_condition\":\"MATCHES_REGEX\",\n       \"matching_strings\":
    \"^user.*(\\/login)$\",\n       \"priority\":\"7\"\n      }\n    ]   \n\n   }"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: bt-config
