apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: configmyapp
  name: configmyapp-st
spec:
  containers:
  - image: appdynamicscx/configmyapp:latest
    name: configmyapp
    imagePullPolicy: Always
    resources: 
      limits:
        cpu: 200m
        memory: 500M
      requests:
        cpu: 100m
        memory: 300M
    env:
    - name: CMA_APPLICATION_NAME
      value: API_Gateway
    - name: CMA_CONTROLLER_HOST
      value: configmyappdemo-2044no-uzyczrm0.appd-cx.com
    - name: CMA_USERNAME
      value: appd
    - name: CMA_PASSWORD
      valueFrom: 
        secretKeyRef:
          name: appd-user-password
          key: cma-password
    envFrom:
      - configMapRef: 
          name: configmyapp-config
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
