title: ConfigMyApp
datatable: true
description: A self-service configuration-as-code tool
show_downloads: true
theme: jekyll-theme-cayman
dockerhuburl: https://hub.docker.com/r/appdynamicscx/configmyapp
