name: Publish Docker image
on:
  release:
    types: [published]
jobs:
  build_and_push_to_registry:
    name: Push ConfigMyApp Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME_CX }}
          password: ${{ secrets.DOCKER_PASSWORD_CX }}
          repository: appdynamicscx/configmyapp
          tags: "latest"
          dockerfile: docker/Dockerfile
      
  test_docker_image:
    name: Docker image QA
    runs-on: ubuntu-latest
    container:
      image: appdynamicscx/configmyapp:latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: TestCase1- Basic and BT configuration
        run: |
          echo Running docker image,
          ./docker/run.sh
       
